<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/fontawesome-free/css/all.min.css')}}">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/jqvmap/jqvmap.min.css')}}">
 <link rel="stylesheet" href="{{asset('public/admin_design/dist/css/adminlte.min.css?v=1')}}"> 
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/daterangepicker/daterangepicker.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/summernote/summernote-bs4.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin_design/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
